import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:my_app/models/event.dart';

class StatsReportService {
  Future<void> generateAndPrintReport({
    Event? event, // Optional for global mode
    required Map<String, dynamic> stats,
    required Map<String, int> security,
    required int totalBooked,
    required int arrived,
    double? globalRevenue, // New for global mode
  }) async {
    final pdf = pw.Document();

    final isGlobal = event == null;
    final revenue = isGlobal ? (globalRevenue ?? 0) : (arrived * event.price);
    final attendanceRate = totalBooked > 0 ? (arrived / totalBooked * 100).toInt() : 0;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text('Sivox ANALYTICS REPORT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey900)),
                        pw.Text(isGlobal ? 'Global Account Summary' : 'Event: ${event.title}', style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                      ],
                    ),
                    pw.Text(DateTime.now().toString().substring(0, 16), style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                  ],
                ),
                pw.Divider(thickness: 2, color: PdfColors.blueGrey100),
                pw.SizedBox(height: 32),

                // Main Stats Grid
                pw.Text('CORE METRICS', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1.2)),
                pw.SizedBox(height: 16),
                pw.TableHelper.fromTextArray(
                  context: context,
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey50),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  data: <List<String>>[
                    <String>['Metric', 'Value'],
                    <String>['Total Revenue', '${revenue.toInt()} DA'],
                    <String>['Total Bookings', '$totalBooked'],
                    <String>['Actual Attendance', '$arrived'],
                    <String>['Attendance Rate', '$attendanceRate%'],
                    if (!isGlobal) <String>['Capacity Used', '${event.maxCapacity != null ? (arrived / event.maxCapacity! * 100).toInt() : 0}%'],
                  ],
                ),
                pw.SizedBox(height: 48),

                // Security Section
                pw.Text('SECURITY & ENFORCEMENT', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, letterSpacing: 1.2)),
                pw.SizedBox(height: 16),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    _statBlock('Ejections', security['ejections']?.toString() ?? '0', PdfColors.orange),
                    _statBlock('Refusals', security['refusals']?.toString() ?? '0', PdfColors.red),
                    _statBlock('Blacklisted', security['blocks']?.toString() ?? '0', PdfColors.purple),
                  ],
                ),
                pw.SizedBox(height: 48),

                // Footer
                pw.Spacer(),
                pw.Divider(color: PdfColors.grey200),
                pw.Center(child: pw.Text('Generated by Sivox Security Management System', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey))),
              ],
            ),
          );
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  pw.Widget _statBlock(String label, String value, PdfColor color) {
    return pw.Container(
      width: 120,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: color, width: 2),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          pw.Text(value, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: color)),
          pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
        ],
      ),
    );
  }

  Future<void> generateLogReport({
    required List<Map<String, dynamic>> logs,
    required String title,
    String? subtitle,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Sivox TACTICAL LEDGER', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey900)),
                      pw.Text(title, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                      if (subtitle != null) pw.Text(subtitle, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                    ],
                  ),
                  pw.Text(DateTime.now().toString().substring(0, 16), style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
                ],
              ),
            ),
            pw.SizedBox(height: 24),
            pw.TableHelper.fromTextArray(
              context: context,
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey50),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 8),
              cellStyle: const pw.TextStyle(fontSize: 7),
              data: <List<String>>[
                <String>['Timestamp', 'Action', 'Agent', 'Description'],
                ...logs.map((L) => [
                  L['created_at'].toString().substring(11, 16),
                  L['action_type'].toString().replaceAll('_', ' '),
                  L['user_name'] ?? 'TERMINAL',
                  L['description'] ?? 'No tactical details.',
                ]),
              ],
            ),
            pw.Footer(
              margin: const pw.EdgeInsets.only(top: 24),
              trailing: pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
