org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:ReservedCodeCacheSize=128m
android.useAndroidX=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.configureondemand=true
org.gradle.vfs.watch=true
org.gradle.workers.max=1
android.aapt2.threadPoolSize=1
kotlin.compiler.execution.strategy=in-process
